name: Smaccer
author: Xenophilicy
version: 2.0.0
description: A massive combination of Slapper and all its add-on plugins
main: Xenophilicy\Smaccer\Smaccer
api: 3.13.0
mcpe-protocol: [361, 388, 389, 390, 407]

permissions:
  smaccer:
    default: op
    description: Allow access to all Smaccer commands
    children:
      smaccer.plus:
        default: op
        description: Allows access to /smaccerplus
      smaccer.create:
        default: op
        description: Allow using command /smaccer create
      smaccer.edit:
        default: op
        description: Allow editing Smaccer entity data with /smaccer edit
      smaccer.rca:
        default: op
        description: Allow running commands as other players
      smaccer.remove:
        default: op
        description: Allow removing Smaccer entities with /smaccer remove [id]
      smaccer.id:
        default: op
        description: Allow viewing entity ID
      smaccer.help:
        default: op
        description: Allow viewing Smaccer help page