# MADE BY:
#  __    __                                          __        __  __  __
# /  |  /  |                                        /  |      /  |/  |/  |
# $$ |  $$ |  ______   _______    ______    ______  $$ |____  $$/ $$ |$$/   _______  __    __
# $$  \/$$/  /      \ /       \  /      \  /      \ $$      \ /  |$$ |/  | /       |/  |  /  |
#  $$  $$<  /$$$$$$  |$$$$$$$  |/$$$$$$  |/$$$$$$  |$$$$$$$  |$$ |$$ |$$ |/$$$$$$$/ $$ |  $$ |
#   $$$$  \ $$    $$ |$$ |  $$ |$$ |  $$ |$$ |  $$ |$$ |  $$ |$$ |$$ |$$ |$$ |      $$ |  $$ |
#  $$ /$$  |$$$$$$$$/ $$ |  $$ |$$ \__$$ |$$ |__$$ |$$ |  $$ |$$ |$$ |$$ |$$ \_____ $$ \__$$ |
# $$ |  $$ |$$       |$$ |  $$ |$$    $$/ $$    $$/ $$ |  $$ |$$ |$$ |$$ |$$       |$$    $$ |
# $$/   $$/  $$$$$$$/ $$/   $$/  $$$$$$/  $$$$$$$/  $$/   $$/ $$/ $$/ $$/  $$$$$$$/  $$$$$$$ |
#                                         $$ |                                      /  \__$$ |
#                                         $$ |                                      $$    $$/
#                                         $$/                                        $$$$$$/
VERSION: "1.2.0" # Internal use only

# Set these add-ons to true or false to enable or disable their features (respectively)

# SlapBack allows Smaccers to hit you back
SlapBack:
  enabled: false

# SmaccerRotation allows nearby Smaccers to look at you
SmaccerRotation:
  enabled: false
  # This is the maximum distance that a Smaccer will target another player
  max-distance: 16

# SmaccerCache allows you to cache or uncache Smaccers
SmaccerCache:
  enabled: false

# SmaccerPlus gives you an easy UI for managing Smaccers
SmaccerPlus:
  enabled: false

# SmaccerCooldown limits how fast a Smaccer can be hit
SmaccerCooldown:
  enabled: false
  # Smaccer hit cooldown (in seconds)
  delay: 0.5
  # This is the message sent when a player attempts to hit a Smaccer too quickly
  message: "§aYou're hitting me too fast!"